### ISSUE TITLE
Crashes on Mac OSX 10.10

### ISSUE THREAD

**Issue by jmeyer2k** [xunkar/llanfair#3]
The program crashes:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: cannot register native hook
	at org.fenix.llanfair.Llanfair.setBehavior(Llanfair.java:624)
	at org.fenix.llanfair.Llanfair.<init>(Llanfair.java:191)
	at org.fenix.llanfair.Llanfair$1.run(Llanfair.java:211)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Might try to fix if I have some time.

**Comment by jmeyer2k** [comment]
Turns out it is just the version posted on the website that doesn't work. Strange.

**Comment by xunkar** [comment]
This crash is due to the impossibility to register the JNativeHook library. You must give Java access to assistive devices for it to work. In 10.9 you would go to System preferences, Security & privacy in the privacy tab. There in accessibility, click the lock and tick the box next to Java JRE or something like this. If this option has moved in 10.10 please let me know.

**Comment by jmeyer2k** [comment]
It hasn't, but it crashed without error after opening the jar, I assumed it
was an error. Version 2 actually has an error message, so unless you want
to add an error to v1, I'd say this issue can be closed. Also, you might be
able to just add some instructions for Mac users on your website. Anyway,
love the tool. Thanks.

**Comment by xunkar** [comment]
You are right. The website is about to be upgraded to a new version, the Llanfair page will have clearer instructions indeed.
